apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-python-project
  namespace: gitops-exercise
  labels:
    app: gitops-python-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-python-project
  template:
    metadata:
      labels:
        app: gitops-python-project
    spec:
      containers:
      - name: gitops-python-project
        image: python-project:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000