apiVersion: v1
kind: Service
metadata:
  name: gitops-python-project
  namespace: gitops-exercise
spec:
  type: NodePort
  selector:
    app: gitops-python-project 
  ports:
    - port: 8081
      targetPort: 5000
      nodePort: 30000